# Generated by Django 3.0.5 on 2020-04-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('highlight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='id_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_highlight_to_tag', to='tag.Tag', verbose_name='tag'),
        ),
    ]
