# Generated by Django 3.0.5 on 2020-04-22 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('highlight', '0002_highlight_id_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_highlight_to_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
