name: reveal
channels:
- conda-forge
dependencies:
  - python=3.6
  - psycopg2
  - pip:
    - Django
    - djangorestframework
    - markdown
    - djangorestframework_simplejwt
    - coreapi
    - gunicorn
    - django-cors-headers
    - Pillow
    - flake8
    - pdfminer.six
    - django-extensions
