FROM continuumio/miniconda:latest

# Install basic shell commands
RUN apt-get update && apt-get install nano

# Install npm
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash - && apt-get install -y nodejs && apt-get install -y npm

# Copy scripts
COPY ./scripts /scripts

# Set permissions for scripts
RUN chmod +x ./scripts*

# Create directories
RUN mkdir -p /frontend
RUN mkdir -p /frontend_tmp

# Install dependencies
WORKDIR frontend_tmp
COPY package.json /frontend_tmp/
RUN npm install

# Build App
COPY . /frontend_tmp
RUN npm run build
#Test