# Generated by Django 3.0.5 on 2020-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDFfile', models.FileField(upload_to='uploads/')),
                ('title', models.CharField(max_length=200)),
                ('content_text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('content_html', models.TextField(blank=True, null=True, verbose_name='html text')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='upload timestamp')),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
