# Generated by Django 3.0.5 on 2020-04-22 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('document', '0002_pdf_id_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_tag_to_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_tag_to_tag', to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='pdf',
            field=models.ManyToManyField(blank=True, null=True, related_name='fk_tag_to_pdf', to='document.PDF', verbose_name='pdf'),
        ),
    ]
